### PR TITLE
Remove psnames module

### PR DESCRIPTION
**Pull request by chrisridd**
This module appears to be useless for fVDI - it provides a way to map
a Unicode name to a Unicode value, and similarly for Postscript names.

However fVDI (and VDI) doesn't use that API or expose it to GEM clients
so it just seems to waste about 64KB RAM.

### CODE REVIEW

**Comment by th-otto** [comment]
Hm, i'll have to check that, but IIRC, that module is still used internally, even when not directly exposed to applications, depending on what mapping tables are present in truetype fonts. And it's definitely needed when someone wants to implement the newer nvdi functions that deal with unicode mappings.

Also i don't think that it does affect performance in any way, just filesize. Is that really an issue?

**Comment by chrisridd** [comment]
Thanks for checking @th-otto . The only related external API I could see was `vqt_char_index()` in NVDI 4 that just takes an unsigned short Unicode value and converts it into an index for the current font, but I may have missed something else.

As to being an issue - it is certainly not for me using Aranym, but I assume there are people using this on actual constrained hardware who might like the saving. But I don't know.

**Comment by mfro0** [comment]
I'm currently inclined to reject that pull request as I'm at the opinion it tries to fix a problem that doesn't really exist.

fVDI users with an Atari clone or accelerator that is powerful enough to run the FreeType module will probably not care (on my FireBee or in Aranym, I personally don't see any noticeable advantage).
fVDI users with a machine that's short on resources first place will most likely refrain from using the FreeType module anyway.

Opinions?

**Comment by chrisridd** [comment]
I understand your argument entirely, and the data point from real hardware is useful. I'm happy to abandon this PR.

**Pull request closed without merging**
